include:
  - paths:
      - './docs/*/**.md'
      - 'README.md'
    # get markdown links
    pattern: !ruby/regexp '/\[[^\]]*\]\(([^\)]*)\)/'
    # ignore links with <!--ignore--> in the line
    exclude_comment: '<!--ignore-->'
    # there are no private GitHub links in here
    private_github: false

